#!/usr/bin/env bash
#
# Copyright (c) 2021, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

basedir="$(dirname "$0")/../../"

"$basedir/scripts/waitForCantonLedgers.sh"

"$basedir/scripts/startTriggers.sh" localhost 5031 triggers/.daml/dist/triggers-1.0.0.dar $(cat "$basedir/canton-bankA.txt")
