#!/usr/bin/env bash
#
# Copyright (c) 2021, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

scripts/waitForLedger.sh localhost 6865
exec scripts/startTriggers.sh localhost 6865 triggers/.daml/dist/triggers-1.0.0.dar
