#!/usr/bin/env bash
#
# Copyright (c) 2021, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

scripts/waitForLedger.sh localhost 6865
scripts/allocateAndInit.sh "$1"
